name: Generate Podcast Video

on:
  workflow_dispatch:
    inputs:
      audio_url:
        description: 'Direct Download Link of the PCM audio file'
        required: true
      video_title:
        description: 'Title of the output video'
        required: true
        default: 'podcast_video'

jobs:
  build-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download Audio from Google Drive
        run: wget -O audio.pcm "${{ github.event.inputs.audio_url }}"

      - name: Combine Image and Audio to Video (9:16)
        # ใช้คำสั่งพิเศษให้อ่านไฟล์เสียงดิบ (s16le, 24000Hz, 1 Channel)
        run: |
          ffmpeg -f s16le -ar 24000 -ac 1 -i audio.pcm -loop 1 -i cover.jpg -c:v libx264 -tune stillimage -c:a aac -b:a 192k -pix_fmt yuv420p -shortest "${{ github.event.inputs.video_title }}.mp4"

      - name: Upload Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Podcast-Video
          path: "*.mp4"
          retention-days: 1
